### ISSUE TITLE
Lock Screen moves to new VD, and it's not removed when unlocked.

### ISSUE THREAD

**Issue by AAlieZZ** [Ubiquitine/MACsimize6#5] opened 2024-08-15 01:55 UTC
OS: Arch Linux
KDE Plasma: 6.1.4

**Comment by azliR** [comment] 2024-08-15 05:08
same here, and also when taking rectangular screenshot using spectacle

**Comment by Ubiquitine** [comment] 2024-08-15 05:30
The issue with lock-screen and logout/restart/shut-down dialog has been addressed in v0.2.7 .
Please confirm that it still happens in the latest 0.2.7 version. 
I'll add more exceptions to fix Spectacle and probably some other apps.

**Comment by azliR** [comment] 2024-08-15 05:34
yes i'm using v0.2.7 and the lock screen still happened, the shutdown and restart is indeed fixed

**Comment by Ubiquitine** [comment] 2024-08-15 07:10
Please test v0.3.0 from the above PR. I added ability to edit filtered window classes and included Spectacle a some more to the default filter.
I still cannot reproduce lock screen issue as it was fixed for me in 0.2.7. I tested it in both Arch and KDE Neon. 
Some user reported that restarting KDE session (logout) seems to resolve similar issues.

**Comment by azliR** [comment] 2024-08-15 11:25
I'm sorry how can i do that? Should i build it first?

**Comment by Ubiquitine** [comment] 2024-08-16 03:56
I've packaged the new version for you. 

1. Download the file [macsimize6-0.3.0.kwinscript.zip](https://github.com/user-attachments/files/16632670/macsimize6-0.3.0.kwinscript.zip)
2. (Optional) Remove ".zip" from the file name so it has an extension ".kwinscript"
3. Open the terminal and cd into the directory containing the files.
4. Run `kpackagetool6 --type=KWin/Script -u macsimize6-0.3.0.kwinscript` .  Alternatively, you can use "KWin Scripts" settings section and click "Install from File..."
5. You might need to logout or restart KWin.

**Comment by Ubiquitine** [comment] 2024-08-17 05:04
UPD:
Added filtering windows without windowClass, which should fix any issues with the lockscreen
Please use this package for testing: [macsimize6-0.3.0.kwinscript.zip](https://github.com/user-attachments/files/16643445/macsimize6-0.3.0.kwinscript.zip)

**Comment by azliR** [comment] 2024-08-17 05:28
i'm sorry i just got time to try, and the last update fixed it all the lockscreen and spectacle, thank you so much for your work!

**Closed** 2024-08-17 05:31 UTC
